name: mytestworkflow

on: push

jobs:
  test_job1:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v4

      - name: welcome
        run: echo "welcome to github action"

      - name: list files
        run: ls
        
      - name: read file
        run: cat README.md  
