name: mytestworkflow

on: push

jobs:
  test_job1:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v4

      - name: install libraries
        run: sudo apt-get install cowsay -y

      - name: execute commands
        run: cowsay -f dragon "run for cow image" >> dragon.txt

      - name: Test file
        run: grep -i "dragon"dragon.txt   

      - name: commands
        run: |
          ls -ltra
          cat README.md
          
