name: mytestworkflow

on: push

jobs:
  test_job1:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v4

      - name: commands
        run: |
          chmod +x commands-script.sh
          ./commands-script.sh
          
