name: mytestworkflow

on: push

jobs:
  test_job1:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v4
       
      - name: list file
        run: ls -ltra    

      - name: commands
        run: |
          chmod +x commandchange-script.sh
          ./commandchange-script.sh
          
